# Generated by Django 5.1.1 on 2026-02-07 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_personnel_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this personnel record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnel',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this personnel record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
