# Generated by Django 5.1.1 on 2026-02-07 03:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_personnel_created_by_personnel_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='can_purge_at',
            field=models.DateTimeField(blank=True, help_text='Date when this record can be permanently deleted (GDPR compliance)', null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='change_reason',
            field=models.TextField(blank=True, help_text='Reason for this change (for audit trail)'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the creator', null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='created_user_agent',
            field=models.TextField(blank=True, help_text='User agent of the creator'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this personnel record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnel',
            name='deleted_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the deleter', null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address (must end with @gmail.com)', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')]),
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for queries'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='retention_period',
            field=models.PositiveIntegerField(blank=True, help_text='Data retention period in days (for compliance)', null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session ID of the last modification', max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='When status was last changed', null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who last changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_status_changed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personnel',
            name='updated_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the last modifier', null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='updated_user_agent',
            field=models.TextField(blank=True, help_text='User agent of the last modifier'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Record version - increments on update'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Archived', 'Archived')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalPersonnel',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=50)),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the creator', null=True)),
                ('created_user_agent', models.TextField(blank=True, help_text='User agent of the creator')),
                ('updated_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the last modifier', null=True)),
                ('updated_user_agent', models.TextField(blank=True, help_text='User agent of the last modifier')),
                ('deleted_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the deleter', null=True)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10, null=True)),
                ('rank', models.CharField(blank=True, choices=[('AM', 'Airman'), ('AW', 'Airwoman'), ('A2C', 'Airman 2nd Class'), ('AW2C', 'Airwoman 2nd Class'), ('A1C', 'Airman 1st Class'), ('AW1C', 'Airwoman 1st Class'), ('SGT', 'Sergeant'), ('SSGT', 'Staff Sergeant'), ('TSGT', 'Technical Sergeant'), ('MSGT', 'Master Sergeant'), ('SMSGT', 'Senior Master Sergeant'), ('CMSGT', 'Chief Master Sergeant'), ('2LT', 'Second Lieutenant'), ('1LT', 'First Lieutenant'), ('CPT', 'Captain'), ('MAJ', 'Major'), ('LTCOL', 'Lieutenant Colonel'), ('COL', 'Colonel'), ('BGEN', 'Brigadier General'), ('MGEN', 'Major General'), ('LTGEN', 'Lieutenant General'), ('GEN', 'General')], help_text='Military rank (not required for superusers)', max_length=20, null=True)),
                ('serial', models.CharField(db_index=True, help_text='Serial number (6 digits for enlisted, or O-XXXXXX for officers)', max_length=20)),
                ('group', models.CharField(choices=[('HAS', 'HAS'), ('951st', '951st'), ('952nd', '952nd'), ('953rd', '953rd')], default='HAS', max_length=10)),
                ('tel', models.CharField(help_text='+639XXXXXXXXX', max_length=13, validators=[django.core.validators.RegexValidator('^\\+639\\d{9}$', 'Phone must be in format +639XXXXXXXXX')])),
                ('email', models.EmailField(blank=True, help_text='Email address (must end with @gmail.com)', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Archived', 'Archived')], default='Active', max_length=20)),
                ('classification', models.CharField(choices=[('ENLISTED PERSONNEL', 'Enlisted Personnel'), ('OFFICER', 'Officer'), ('SUPERUSER', 'Superuser')], default='ENLISTED PERSONNEL', help_text='Personnel classification (ENLISTED PERSONNEL, OFFICER, SUPERUSER)', max_length=20)),
                ('picture', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp - record kept for reference', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for queries')),
                ('version', models.PositiveIntegerField(default=1, help_text='Record version - increments on update')),
                ('change_reason', models.TextField(blank=True, help_text='Reason for this change (for audit trail)')),
                ('status_changed_at', models.DateTimeField(blank=True, help_text='When status was last changed', null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session ID of the last modification', max_length=100)),
                ('retention_period', models.PositiveIntegerField(blank=True, help_text='Data retention period in days (for compliance)', null=True)),
                ('can_purge_at', models.DateTimeField(blank=True, help_text='Date when this record can be permanently deleted (GDPR compliance)', null=True)),
                ('history_change_reason', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this personnel record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this personnel record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last modified this personnel record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status_changed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last changed the status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Personnel',
                'verbose_name_plural': 'historical Personnel',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
