# Generated by Django 5.1.1 on 2026-02-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_personnel_can_purge_at_personnel_change_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonnel',
            name='serial',
            field=models.CharField(db_index=True, help_text='Serial number (numeric only)', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='serial',
            field=models.CharField(help_text='Serial number (numeric only)', max_length=20, unique=True),
        ),
    ]
