# Generated by Django 5.1.1 on 2026-02-11 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_alter_historicalpersonnel_serial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonnel',
            name='serial',
            field=models.CharField(db_index=True, help_text='Serial number (officers have O- prefix, enlisted are numeric only)', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='serial',
            field=models.CharField(help_text='Serial number (officers have O- prefix, enlisted are numeric only)', max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['status', 'classification'], name='personnel_status_25b77e_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['rank'], name='personnel_rank_428292_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['group'], name='personnel_group_789d05_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['-registration_date'], name='personnel_registr_176507_idx'),
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Active', 'Inactive', 'Suspended', 'Archived'])), name='valid_personnel_status'),
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.CheckConstraint(condition=models.Q(('classification__in', ['ENLISTED PERSONNEL', 'OFFICER', 'SUPERUSER'])), name='valid_personnel_classification'),
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.CheckConstraint(condition=models.Q(('serial', ''), _negated=True), name='serial_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.CheckConstraint(condition=models.Q(('email__icontains', '@'), ('email', ''), _connector='OR'), name='valid_email_format'),
        ),
    ]
