# ============================================================================
# ARMGUARD UNIFIED REDIS CONFIGURATION
# Generated by Unified Redis Management System
# ============================================================================

import redis
from django.core.exceptions import ImproperlyConfigured
from decouple import config

# Redis connection configuration
REDIS_CONFIG = {
    'host': config('REDIS_HOST', default='127.0.0.1'),
    'port': config('REDIS_PORT', default=6379, cast=int),
    'password': config('REDIS_PASSWORD', default=''),
    'db': config('REDIS_DB', default=1, cast=int),
    'socket_connect_timeout': 2,
    'socket_timeout': 2,
    'retry_on_timeout': True,
    'health_check_interval': 30,
}

def get_redis_connection():
    """Get Redis connection with error handling"""
    try:
        client = redis.Redis(**REDIS_CONFIG)
        client.ping()  # Test connection
        return client
    except (redis.ConnectionError, redis.TimeoutError) as e:
        raise ImproperlyConfigured(f"Redis connection failed: {e}")

# Test Redis availability
try:
    REDIS_AVAILABLE = True
    get_redis_connection()
    print("✅ Redis connection successful - WebSocket optimization enabled")
except ImproperlyConfigured:
    REDIS_AVAILABLE = False
    print("⚠️  Redis connection failed - falling back to InMemory channels")

# Django Channels configuration with Redis
if REDIS_AVAILABLE:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [(REDIS_CONFIG['host'], REDIS_CONFIG['port'])],
                "password": REDIS_CONFIG['password'] if REDIS_CONFIG['password'] else None,
                "capacity": 300,  # Maximum messages in channel
                "expiry": 60,     # Message expiry (seconds)
                "group_expiry": 86400,  # Group expiry (24 hours)
                "prefix": "armguard:",  # Redis key prefix
                "symmetric_encryption_keys": [config('DJANGO_SECRET_KEY', default='armguard-websocket-encryption')[:32]],
            },
        },
    }
else:
    # Fallback to InMemory with optimized settings
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
            'CONFIG': {
                "capacity": 100,   # Reduced for memory efficiency
                "expiry": 30,     # Shorter expiry
            },
        },
    }

# WebSocket-specific settings
WEBSOCKET_SETTINGS = {
    'connection_timeout': 300,    # 5 minutes
    'heartbeat_interval': 30,     # 30 second heartbeat
    'max_connections_per_user': 5,
    'message_buffer_size': 100,
    'enable_compression': True,
}

# Caching configuration (separate from Channels)
if REDIS_AVAILABLE:
    cache_location = f"redis://{REDIS_CONFIG['host']}:{REDIS_CONFIG['port']}/0"
    if REDIS_CONFIG['password']:
        cache_location = f"redis://:{REDIS_CONFIG['password']}@{REDIS_CONFIG['host']}:{REDIS_CONFIG['port']}/0"
    
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': cache_location,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'armguard-cache',
            'TIMEOUT': 300,  # 5 minutes default
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'armguard-cache',
        }
    }

print(f"🔄 Channel Backend: {'Redis' if REDIS_AVAILABLE else 'InMemory'}")
print(f"💾 Cache Backend: {'Redis' if REDIS_AVAILABLE else 'Local Memory'}")