# Generated by Django 5.1.1 on 2026-01-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_handler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrintConfiguration',
        ),
    ]
