# Generated by Django 5.1.1 on 2026-02-20 05:33

import core.device.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_token', models.CharField(default=core.device.models._generate_device_token, help_text='Server-issued device identity token (64-char hex). Never transmitted in plain URL.', max_length=64, unique=True)),
                ('public_key_pem', models.TextField(blank=True, help_text='PEM public key for challenge-response cryptographic binding (optional).')),
                ('public_key_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(blank=True, help_text="E.g. 'workstation', 'armory-terminal', 'mobile'", max_length=64)),
                ('ip_first_seen', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_last_seen', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_binding', models.GenericIPAddressField(blank=True, help_text='If set, device is only authorized from this exact IP.', null=True)),
                ('user_agent_hash', models.CharField(blank=True, help_text='SHA-256[:16] of HTTP_USER_AGENT at registration time.', max_length=64)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=core.device.models._default_expires_at)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_MFA', 'Pending MFA Verification'), ('PENDING', 'Pending Admin Approval'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING_MFA', max_length=20)),
                ('security_tier', models.CharField(choices=[('STANDARD', 'Standard'), ('RESTRICTED', 'Restricted'), ('HIGH_SECURITY', 'High Security'), ('MILITARY', 'Military Grade')], default='HIGH_SECURITY', max_length=20)),
                ('can_transact', models.BooleanField(default=False)),
                ('max_daily_transactions', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('active_hours_start', models.TimeField(blank=True, null=True)),
                ('active_hours_end', models.TimeField(blank=True, null=True)),
                ('authorized_roles', models.JSONField(blank=True, default=list, help_text='List of role names permitted on this device.')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='0=clean, 100=maximum risk. Auto-updated by anomaly detection.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('failed_auth_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('enrollment_reason', models.TextField(blank=True, help_text='Requester-provided justification.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('last_revalidated_at', models.DateTimeField(blank=True, null=True)),
                ('revalidation_required', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who enrolled this device.', on_delete=django.db.models.deletion.CASCADE, related_name='authorized_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorized Device',
                'verbose_name_plural': 'Authorized Devices',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_token_prefix', models.CharField(blank=True, help_text='First 8 chars of device_token for correlation without exposing full secret.', max_length=8)),
                ('user_agent', models.TextField(blank=True)),
                ('security_level', models.CharField(default='RESTRICTED', max_length=20)),
                ('is_authorized', models.BooleanField(default=False)),
                ('denial_reason', models.CharField(blank=True, max_length=255)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('risk_score_at_check', models.PositiveSmallIntegerField(default=0)),
                ('siem_metadata', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='core.authorizeddevice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_device_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ENROLLED', 'Device Enrolled'), ('MFA_PASSED', 'MFA Challenge Passed'), ('MFA_FAILED', 'MFA Challenge Failed'), ('ACTIVATED', 'Device Activated'), ('REVOKED', 'Device Revoked'), ('SUSPENDED', 'Device Suspended'), ('EXPIRED', 'Authorization Expired'), ('REVALIDATED', 'Device Re-validated'), ('LOCKED_OUT', 'Device Locked Out'), ('LOCK_CLEARED', 'Lockout Cleared'), ('TOKEN_ROTATED', 'Token Rotated'), ('RISK_UPDATED', 'Risk Score Updated'), ('IP_ANOMALY', 'IP Anomaly Detected'), ('AUTH_SUCCESS', 'Authorization Success'), ('AUTH_DENIED', 'Authorization Denied')], db_index=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this event (null for automated events).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_device_audit_events', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.authorizeddevice')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceMFAChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('TOTP', 'Authenticator App (TOTP)'), ('EMAIL', 'Email OTP')], default='TOTP', max_length=10)),
                ('otp_hash', models.CharField(blank=True, max_length=64)),
                ('otp_salt', models.CharField(blank=True, max_length=32)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenge', to='core.authorizeddevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceRiskEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('risk_type', models.CharField(choices=[('NEW_IP', 'New IP Address'), ('IP_OUTSIDE', 'IP Outside Expected Range'), ('OFF_HOURS', 'Access Outside Active Hours'), ('HIGH_VELOCITY', 'High Request Velocity'), ('FAILED_ATTEMPTS', 'Repeated Failed Attempts'), ('CONCURRENT_IP', 'Concurrent Access from Different IPs'), ('UA_CHANGE', 'User-Agent Changed'), ('SUSPICIOUS_PATH', 'Access to Sensitive Path')], db_index=True, max_length=30)),
                ('severity', models.PositiveSmallIntegerField(default=10, help_text='Points added to device risk score (1-50).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_risk_events', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='core.authorizeddevice')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='authorizeddevice',
            index=models.Index(fields=['user', 'status'], name='core_author_user_id_f97a46_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizeddevice',
            index=models.Index(fields=['device_token'], name='core_author_device__dadd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizeddevice',
            index=models.Index(fields=['status', 'expires_at'], name='core_author_status_2fab1a_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizeddevice',
            index=models.Index(fields=['ip_last_seen', '-last_used'], name='core_author_ip_last_f16758_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizeddevice',
            index=models.Index(fields=['risk_score', 'status'], name='core_author_risk_sc_7c8de4_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaccesslog',
            index=models.Index(fields=['-checked_at'], name='core_device_checked_3f2869_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaccesslog',
            index=models.Index(fields=['device', '-checked_at'], name='core_device_device__1bb59c_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaccesslog',
            index=models.Index(fields=['is_authorized', '-checked_at'], name='core_device_is_auth_323435_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaccesslog',
            index=models.Index(fields=['ip_address', '-checked_at'], name='core_device_ip_addr_7766a1_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaccesslog',
            index=models.Index(fields=['user', '-checked_at'], name='core_device_user_id_4f12ad_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceauditevent',
            index=models.Index(fields=['device', '-occurred_at'], name='core_device_device__1efc30_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceauditevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='core_device_event_t_22c59b_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceauditevent',
            index=models.Index(fields=['actor', '-occurred_at'], name='core_device_actor_i_ae7186_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceriskevent',
            index=models.Index(fields=['device', 'acknowledged', '-detected_at'], name='core_device_device__9a61d5_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceriskevent',
            index=models.Index(fields=['risk_type', '-detected_at'], name='core_device_risk_ty_5d150c_idx'),
        ),
    ]
