#!/bin/bash

################################################################################
# ArmGuard Device Authorization Guide
# Shows how to register and authorize different types of devices
################################################################################

echo "🔐 ArmGuard Device Authorization Methods"
echo "========================================"
echo ""

# Get current system info
LAN_IP=$(hostname -I | cut -d' ' -f1)

echo "📋 Your ArmGuard System Info:"
echo "  • Server IP: $LAN_IP"
echo "  • Admin Panel: http://$LAN_IP/admin"
echo "  • Main Interface: http://$LAN_IP"
echo ""

echo "🖥️  DEVICE AUTHORIZATION METHODS:"
echo ""

echo "1️⃣  LAN DEVICES (Local Network Access)"
echo "======================================="
echo "For PCs on your local network (192.168.x.x):"
echo ""
echo "• ✅ AUTOMATIC: All devices on LAN (192.168.x.x) are pre-authorized"
echo "• ✅ FULL ACCESS: Can perform all armory transactions"
echo "• ✅ NO SETUP NEEDED: Just browse to http://$LAN_IP"
echo ""
echo "Examples of authorized LAN devices:"
echo "  - Armory Desktop PC: 192.168.0.100"
echo "  - Office Laptop: 192.168.0.150"  
echo "  - Admin Workstation: 192.168.0.200"
echo ""

echo "2️⃣  VPN REMOTE DEVICES (Secure Remote Access)"
echo "=============================================="
echo "For remote devices that need secure access:"
echo ""
echo "Generate VPN client configurations:"
echo "  cd /home/armguard/armguard/deployment"
echo "  sudo ./rpi4b-generate-client.sh device-name role"
echo ""
echo "Available roles:"
echo "  • commander  - Full inventory viewing, reports, user management"
echo "  • armorer    - Equipment inventory, maintenance reports" 
echo "  • emergency  - Critical equipment access only"
echo "  • personnel  - Personal transaction history only"
echo ""
echo "Example commands:"
echo "  sudo ./rpi4b-generate-client.sh johns-laptop commander"
echo "  sudo ./rpi4b-generate-client.sh office-tablet armorer"
echo "  sudo ./rpi4b-generate-client.sh mobile-phone personnel"
echo ""

echo "3️⃣  USER ACCOUNT REGISTRATION"
echo "=============================="
echo "Create user accounts in Django admin:"
echo ""
echo "1. Visit: http://$LAN_IP/admin"
echo "2. Log in with superuser account"
echo "3. Go to 'Users' section"
echo "4. Click 'Add User'"
echo "5. Fill in user details and permissions"
echo ""

echo "4️⃣  DEVICE MAC ADDRESS AUTHORIZATION (Advanced)"
echo "==============================================="
echo "For strict device control, you can:"
echo ""
echo "1. Get device MAC address: ipconfig /all (Windows) or ifconfig (Linux)"
echo "2. Add to authorized devices list in Django admin"
echo "3. Configure network middleware to check MAC addresses"
echo ""

echo ""
echo "🔧 QUICK SETUP EXAMPLES:"
echo "========================"
echo ""

echo "A) Register Office PC for LAN access:"
echo "   • No setup needed - just use http://$LAN_IP"
echo "   • Create user account in admin panel"
echo ""

echo "B) Register Remote Laptop with VPN:"
echo "   sudo ./rpi4b-generate-client.sh office-laptop commander"
echo "   • Install WireGuard on laptop"
echo "   • Import generated .conf file"
echo "   • Access via http://10.0.0.1"
echo ""

echo "C) Register Mobile Device:"
echo "   sudo ./rpi4b-generate-client.sh phone-admin personnel"
echo "   • Install WireGuard app"
echo "   • Scan generated QR code"
echo "   • Limited access via VPN"
echo ""

echo ""
echo "📱 STEP-BY-STEP DEVICE REGISTRATION:"
echo "===================================="
echo ""

# Create superuser if needed
echo "Step 1: Create admin account (if not done yet)"
echo "   cd /opt/armguard"
echo "   source venv/bin/activate" 
echo "   python manage.py createsuperuser"
echo ""

echo "Step 2: Log into admin panel"
echo "   Visit: http://$LAN_IP/admin"
echo "   Use superuser credentials"
echo ""

echo "Step 3: Register devices based on access type"
echo "   • LAN devices: Create user accounts only"
echo "   • VPN devices: Generate VPN configs + create user accounts"
echo ""

echo "Step 4: Test access"
echo "   • LAN: Direct access to http://$LAN_IP"
echo "   • VPN: Connect VPN, then access http://10.0.0.1"
echo ""

echo "🛡️  SECURITY LEVELS:"
echo "===================="
echo ""
echo "🔴 HIGH SECURITY (LAN Only):"
echo "   • Physical network access required"
echo "   • Full transaction capabilities"
echo "   • No remote access"
echo ""
echo "🟡 MEDIUM SECURITY (VPN):"  
echo "   • Encrypted remote access"
echo "   • Role-based permissions"
echo "   • Read-only for most operations"
echo ""
echo "🟢 BASIC SECURITY (WAN - if enabled):"
echo "   • Internet access"  
echo "   • Read-only status checking only"
echo "   • Limited functionality"
echo ""

echo ""
echo "💡 RECOMMENDATIONS:"
echo "===================="
echo ""
echo "For Military/Secure Environment:"
echo "  ✅ Use LAN access for all armory transactions"
echo "  ✅ Use VPN only for status monitoring"
echo "  ✅ Create separate user accounts for each person"
echo "  ✅ Regularly rotate VPN client certificates"
echo ""

echo "Next steps to register your first device:"
echo "1. Create superuser: cd /opt/armguard && source venv/bin/activate && python manage.py createsuperuser"
echo "2. Access admin: http://$LAN_IP/admin"
echo "3. Add users and generate VPN configs as needed"
echo ""

echo "For VPN client generation, run:"
echo "cd /home/armguard/armguard/deployment && sudo ./rpi4b-generate-client.sh device-name role"