# Generated by Django 5.1.1 on 2026-02-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_add_integrity_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='valid_transaction_action',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='positive_mags_count',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='positive_rounds_count',
        ),
    ]
