# Generated by Django 5.1.1 on 2026-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_valid_transaction_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='print_priority',
            field=models.BooleanField(default=False, help_text='Indicates transaction needs immediate PDF printing'),
        ),
    ]
