# Generated by Django 5.1.1 on 2026-02-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_print_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='print_priority',
        ),
    ]
