#!/bin/bash

# =============================================================================
# 04_MONITORING.SH - LOGGING, METRICS, AND HEALTH CHECKS
# =============================================================================
# PURPOSE: Monitoring setup, health checks, performance validation
# INTEGRATED: Monitoring from deployment_A docker-testing + operational monitoring
# VERSION: 4.0.0 - Modular Deployment System
# =============================================================================

set -e  # Exit on any error
set -u  # Exit on undefined variables

# =============================================================================
# CONFIGURATION AND CONSTANTS
# =============================================================================

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly LOG_DIR="/var/log/armguard-deploy"
readonly LOG_FILE="$LOG_DIR/04-monitoring-$(date +%Y%m%d-%H%M%S).log"
readonly ARMGUARD_ROOT="$(dirname "$SCRIPT_DIR")"

# Load configuration
if [ -f "$SCRIPT_DIR/master-config.sh" ]; then
    source "$SCRIPT_DIR/master-config.sh"
fi

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly PURPLE='\033[0;35m'
readonly CYAN='\033[0;36m'
readonly WHITE='\033[1;37m'
readonly NC='\033[0m'

# Monitoring configuration
MONITORING_TYPE="${MONITORING_TYPE:-operational}"  # operational, full, minimal
PROJECT_NAME="${PROJECT_NAME:-armguard}"
DEFAULT_DOMAIN="${DEFAULT_DOMAIN:-armguard.local}"

# =============================================================================
# LOGGING SYSTEM
# =============================================================================

log_info() {
    echo -e "${GREEN}[MONITOR-INFO]${NC} $*" | tee -a "$LOG_FILE"
}

log_warn() {
    echo -e "${YELLOW}[MONITOR-WARN]${NC} $*" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[MONITOR-ERROR]${NC} $*" | tee -a "$LOG_FILE"
}

log_success() {
    echo -e "${CYAN}[MONITOR-SUCCESS]${NC} $*" | tee -a "$LOG_FILE"
}

# =============================================================================
# MONITORING CONFIGURATION SELECTION
# =============================================================================

select_monitoring_type() {
    clear
    echo -e "${BLUE}╔═══════════════════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║                                                                               ║${NC}"
    echo -e "${BLUE}║              ${WHITE}📊 ARMGUARD MONITORING SETUP${BLUE}                              ║${NC}"
    echo -e "${BLUE}║                    ${CYAN}Phase 4: Monitoring and Health Checks${BLUE}                 ║${NC}"
    echo -e "${BLUE}║                                                                               ║${NC}"
    echo -e "${BLUE}╚═══════════════════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    log_info "Selecting monitoring configuration..."
    
    echo -e "${WHITE}📊 Monitoring Configuration Options:${NC}"
    echo "1. Minimal monitoring (basic health checks, log collection)"
    echo "2. Operational monitoring (system metrics, service health, alerts)"
    echo "3. Full monitoring stack (Prometheus, Grafana, comprehensive dashboards)"
    echo ""
    
    while true; do
        read -p "Select monitoring type (1-3): " monitor_choice
        case $monitor_choice in
            1)
                MONITORING_TYPE="minimal"
                log_info "Minimal monitoring selected"
                break
                ;;
            2)
                MONITORING_TYPE="operational"
                log_info "Operational monitoring selected"
                break
                ;;
            3)
                MONITORING_TYPE="full"
                log_info "Full monitoring stack selected"
                break
                ;;
            *)
                echo "Invalid choice. Please select 1, 2, or 3."
                ;;
        esac
    done
    
    echo ""
}

# =============================================================================
# BASIC HEALTH CHECKS (ALL MONITORING TYPES)
# =============================================================================

setup_health_checks() {
    log_info "Setting up basic health checks..."
    
    # Create health check script
    local health_script="/usr/local/bin/armguard-health-check"
    
    sudo tee "$health_script" > /dev/null << 'EOF'
#!/bin/bash
# ArmGuard Health Check Script
# Generated by 04_monitoring.sh

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Health check functions
check_service() {
    local service_name="$1"
    if systemctl is-active --quiet "$service_name" 2>/dev/null; then
        echo -e "${GREEN}✅ $service_name${NC}: Running"
        return 0
    else
        echo -e "${RED}❌ $service_name${NC}: Not running"
        return 1
    fi
}

check_port() {
    local port="$1"
    local description="$2"
    if nc -z localhost "$port" 2>/dev/null; then
        echo -e "${GREEN}✅ $description${NC}: Port $port accessible"
        return 0
    else
        echo -e "${RED}❌ $description${NC}: Port $port not accessible"
        return 1
    fi
}

check_database() {
    if sudo -u postgres pg_isready >/dev/null 2>&1; then
        echo -e "${GREEN}✅ PostgreSQL${NC}: Database accessible"
        return 0
    else
        echo -e "${RED}❌ PostgreSQL${NC}: Database not accessible"
        return 1
    fi
}

check_redis() {
    if redis-cli ping >/dev/null 2>&1; then
        echo -e "${GREEN}✅ Redis${NC}: Cache accessible"
        return 0
    else
        echo -e "${RED}❌ Redis${NC}: Cache not accessible"
        return 1
    fi
}

# Main health check
echo "🏥 ArmGuard Health Check - $(date)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

health_status=0

# Check core services
check_service "armguard-gunicorn" || health_status=1
check_service "armguard-daphne" || health_status=1
check_service "nginx" || health_status=1
check_service "postgresql" || health_status=1
check_service "redis-server" || check_service "redis" || health_status=1

echo ""

# Check network connectivity
check_port "8000" "Gunicorn (HTTP)" || health_status=1
check_port "8001" "Daphne (WebSocket)" || health_status=1
check_port "80" "Nginx (HTTP)" || health_status=1
check_port "443" "Nginx (HTTPS)" || check_port "8443" "Nginx (HTTPS Alt)" || health_status=1

echo ""

# Check application components
check_database || health_status=1
check_redis || health_status=1

echo ""

# Overall status
if [ $health_status -eq 0 ]; then
    echo -e "${GREEN}✅ Overall Status: All systems operational${NC}"
else
    echo -e "${RED}❌ Overall Status: Some issues detected${NC}"
fi

exit $health_status
EOF
    
    sudo chmod +x "$health_script"
    log_success "Health check script created at $health_script"
    
    # Create systemd timer for periodic health checks
    local health_service="/etc/systemd/system/armguard-health-check.service"
    local health_timer="/etc/systemd/system/armguard-health-check.timer"
    
    sudo tee "$health_service" > /dev/null << EOF
[Unit]
Description=ArmGuard Health Check
Documentation=man:armguard-health-check

[Service]
Type=oneshot
ExecStart=/usr/local/bin/armguard-health-check
User=root
StandardOutput=journal
StandardError=journal
EOF
    
    sudo tee "$health_timer" > /dev/null << EOF
[Unit] 
Description=Run ArmGuard Health Check every 5 minutes
Requires=armguard-health-check.service

[Timer]
OnCalendar=*:0/5
Persistent=true

[Install]
WantedBy=timers.target
EOF
    
    sudo systemctl daemon-reload
    sudo systemctl enable armguard-health-check.timer
    sudo systemctl start armguard-health-check.timer
    
    log_success "Periodic health checks enabled (every 5 minutes)"
}

# =============================================================================
# LOG AGGREGATION AND MONITORING
# =============================================================================

setup_log_monitoring() {
    log_info "Setting up log monitoring..."
    
    # Create log monitoring script
    local log_monitor="/usr/local/bin/armguard-log-monitor"
    
    sudo tee "$log_monitor" > /dev/null << 'EOF'
#!/bin/bash
# ArmGuard Log Monitor
# Monitors application logs for errors and issues

LOG_FILES=(
    "/var/log/armguard/django.log"
    "/var/log/armguard/gunicorn.log" 
    "/var/log/armguard/daphne-access.log"
    "/var/log/nginx/access.log"
    "/var/log/nginx/error.log"
)

ERROR_PATTERNS=(
    "ERROR"
    "CRITICAL" 
    "FATAL"
    "Exception"
    "500 Internal"
    "502 Bad Gateway"
    "503 Service Unavailable"
    "Connection refused"
)

echo "📋 ArmGuard Log Monitor - $(date)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

for log_file in "${LOG_FILES[@]}"; do
    if [ -f "$log_file" ]; then
        echo "Checking $log_file..."
        
        # Check for recent errors (last 1 hour)
        recent_errors=$(find "$log_file" -mmin -60 -exec grep -i -E "$(IFS='|'; echo "${ERROR_PATTERNS[*]}")" {} \; 2>/dev/null | wc -l)
        
        if [ "$recent_errors" -gt 0 ]; then
            echo "  ⚠️  Found $recent_errors recent errors"
            
            # Show last few errors
            grep -i -E "$(IFS='|'; echo "${ERROR_PATTERNS[*]}")" "$log_file" | tail -3 | while read line; do
                echo "    $line"
            done
        else
            echo "  ✅ No recent errors"
        fi
    else
        echo "  ❓ $log_file not found"
    fi
    echo ""
done
EOF
    
    sudo chmod +x "$log_monitor"
    log_success "Log monitoring script created"
    
    # Set up log rotation if not already configured
    if [ ! -f "/etc/logrotate.d/armguard" ]; then
        sudo tee "/etc/logrotate.d/armguard" > /dev/null << EOF
/var/log/armguard/*.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    create 644 www-data www-data
    postrotate
        systemctl reload armguard-gunicorn armguard-daphne 2>/dev/null || true
    endscript
}
EOF
        log_success "Log rotation configured"
    fi
}

# =============================================================================
# OPERATIONAL MONITORING (SYSTEM METRICS)
# =============================================================================

setup_operational_monitoring() {
    log_info "Setting up operational monitoring..."
    
    # Install system monitoring tools
    case "$(. /etc/os-release; echo $ID)" in
        "ubuntu"|"debian")
            sudo apt update -qq
            sudo apt install -y htop iotop nethogs sysstat
            ;;
        "centos"|"rhel"|"fedora")
            if command -v dnf >/dev/null 2>&1; then
                sudo dnf install -y htop iotop-c nethogs sysstat
            else
                sudo yum install -y htop iotop nethogs sysstat
            fi
            ;;
    esac
    
    # Enable sysstat (system activity reporter)
    sudo systemctl enable sysstat
    sudo systemctl start sysstat
    
    # Create system metrics collector
    local metrics_script="/usr/local/bin/armguard-metrics"
    
    sudo tee "$metrics_script" > /dev/null << 'EOF'
#!/bin/bash
# ArmGuard System Metrics Collector

echo "📊 ArmGuard System Metrics - $(date)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# System load
echo "🖥️  System Load:"
uptime

echo ""

# Memory usage
echo "💾 Memory Usage:"
free -h

echo ""

# Disk usage
echo "💿 Disk Usage:"
df -h / /var

echo ""

# Network connections
echo "🌐 Network Connections:"
ss -tuln | grep -E "(8000|8001|443|80|5432|6379)"

echo ""

# Process status
echo "⚙️  ArmGuard Processes:"
ps aux | grep -E "(gunicorn|daphne|nginx|postgres|redis)" | grep -v grep

echo ""

# Recent system errors
echo "⚠️  Recent System Errors:"
journalctl --since "1 hour ago" --priority err --no-pager | tail -5
EOF
    
    sudo chmod +x "$metrics_script"
    log_success "System metrics collector created"
    
    # Create performance monitoring cron job
    (crontab -l 2>/dev/null; echo "*/15 * * * * /usr/local/bin/armguard-metrics >> /var/log/armguard/metrics.log 2>&1") | crontab -
    log_success "Performance monitoring scheduled (every 15 minutes)"
}

# =============================================================================
# FULL MONITORING STACK (PROMETHEUS + GRAFANA)
# =============================================================================

setup_full_monitoring() {
    log_info "Setting up full monitoring stack..."
    
    # Check if Docker is available
    if ! command -v docker >/dev/null 2>&1; then
        log_warn "Docker not available - installing full monitoring requires Docker"
        log_info "Installing Docker..."
        
        # Install Docker (Ubuntu/Debian)
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker "$USER"
        sudo systemctl enable docker
        sudo systemctl start docker
        
        log_success "Docker installed successfully"
    fi
    
    # Create monitoring stack directory
    local monitoring_dir="/opt/armguard-monitoring"
    sudo mkdir -p "$monitoring_dir"
    
    # Create docker-compose for monitoring stack (from deployment_A/methods/docker-testing)
    sudo tee "$monitoring_dir/docker-compose.yml" > /dev/null << EOF
version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: armguard-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: armguard-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=armguard2024
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: armguard-node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: armguard-redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=host.docker.internal:6379
    restart: unless-stopped

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: armguard-postgres-exporter
    ports:  
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres@host.docker.internal:5432/postgres?sslmode=disable
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: armguard-monitoring
EOF
    
    # Create Prometheus configuration
    sudo tee "$monitoring_dir/prometheus.yml" > /dev/null << EOF
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'armguard-system'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'armguard-redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'armguard-postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'armguard-application'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
EOF
    
    # Create Grafana provisioning directory
    sudo mkdir -p "$monitoring_dir/grafana/provisioning/datasources"
    sudo tee "$monitoring_dir/grafana/provisioning/datasources/datasources.yml" > /dev/null << EOF
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
EOF
    
    # Set permissions
    sudo chmod -R 755 "$monitoring_dir"
    
    # Start monitoring stack
    cd "$monitoring_dir"
    sudo docker-compose up -d
    
    if [ $? -eq 0 ]; then
        log_success "Full monitoring stack deployed successfully"
        log_info "Grafana available at: http://localhost:3000 (admin/armguard2024)"
        log_info "Prometheus available at: http://localhost:9090"
    else
        log_error "Failed to deploy monitoring stack"
        return 1
    fi
}

# =============================================================================
# MONITORING VALIDATION
# =============================================================================

validate_monitoring() {
    log_info "Validating monitoring setup..."
    
    local validation_passed=true
    
    # Test health check script
    if /usr/local/bin/armguard-health-check >/dev/null 2>&1; then
        log_success "Health check script working"
    else
        log_warn "Health check script has issues"
    fi
    
    # Check if health check timer is active
    if systemctl is-active --quiet armguard-health-check.timer; then
        log_success "Health check timer is active"
    else
        log_warn "Health check timer not running"
        validation_passed=false
    fi
    
    # Check log monitoring
    if [ -x "/usr/local/bin/armguard-log-monitor" ]; then
        log_success "Log monitoring script available"
    else
        log_warn "Log monitoring script not found"
    fi
    
    # Validate monitoring type specific components
    case "$MONITORING_TYPE" in
        "operational")
            if command -v iotop >/dev/null 2>&1 && command -v htop >/dev/null 2>&1; then
                log_success "System monitoring tools installed"
            else
                log_warn "Some system monitoring tools missing"
            fi
            ;;
        "full")
            if docker ps | grep -q armguard-prometheus; then
                log_success "Prometheus container running"
            else
                log_warn "Prometheus container not running"
                validation_passed=false
            fi
            
            if docker ps | grep -q armguard-grafana; then
                log_success "Grafana container running"
            else
                log_warn "Grafana container not running"
                validation_passed=false
            fi
            ;;
    esac
    
    return $([ "$validation_passed" = true ] && echo 0 || echo 1)
}

# =============================================================================
# MAIN MONITORING EXECUTION
# =============================================================================

main() {
    log_info "Starting ArmGuard monitoring setup..."
    log_info "Logging to: $LOG_FILE"
    
    # Select monitoring type
    select_monitoring_type
    
    echo -e "${YELLOW}🔧 Setting up basic monitoring...${NC}"
    setup_health_checks
    setup_log_monitoring
    
    # Setup additional monitoring based on type
    case "$MONITORING_TYPE" in
        "operational")
            echo -e "${YELLOW}📊 Setting up operational monitoring...${NC}"
            setup_operational_monitoring
            ;;
        "full")
            echo -e "${YELLOW}🚀 Setting up full monitoring stack...${NC}"
            setup_operational_monitoring
            setup_full_monitoring
            ;;
        "minimal")
            log_info "Minimal monitoring selected - basic setup complete"
            ;;
    esac
    
    echo -e "${YELLOW}✅ Validating monitoring setup...${NC}"
    sleep 5
    
    if validate_monitoring; then
        echo ""
        log_success "✅ Monitoring setup completed successfully!"
        echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════════════════════╗${NC}"
        echo -e "${GREEN}║                       ${WHITE}MONITORING SETUP COMPLETED${GREEN}                          ║${NC}"
        echo -e "${GREEN}║                                                                               ║${NC}"
        case "$MONITORING_TYPE" in
            "minimal")
                echo -e "${GREEN}║  Minimal Monitoring Active:                                                  ║${NC}"
                echo -e "${GREEN}║  • ${WHITE}Health checks${GREEN}: Every 5 minutes                                        ║${NC}"
                echo -e "${GREEN}║  • ${WHITE}Log monitoring${GREEN}: Error detection and rotation                        ║${NC}"
                ;;
            "operational")
                echo -e "${GREEN}║  Operational Monitoring Active:                                              ║${NC}"
                echo -e "${GREEN}║  • ${WHITE}Health checks${GREEN}: Every 5 minutes                                        ║${NC}"
                echo -e "${GREEN}║  • ${WHITE}System metrics${GREEN}: Every 15 minutes                                    ║${NC}"
                echo -e "${GREEN}║  • ${WHITE}Log monitoring${GREEN}: Error detection and analysis                        ║${NC}"
                ;;
            "full")
                echo -e "${GREEN}║  Full Monitoring Stack Active:                                               ║${NC}"
                echo -e "${GREEN}║  • ${WHITE}Grafana Dashboard${GREEN}: http://localhost:3000                             ║${NC}"  
                echo -e "${GREEN}║  • ${WHITE}Prometheus Metrics${GREEN}: http://localhost:9090                           ║${NC}"
                echo -e "${GREEN}║  • ${WHITE}System monitoring${GREEN}: Node, Redis, PostgreSQL exporters              ║${NC}"
                echo -e "${GREEN}║  • ${WHITE}Health checks${GREEN} and ${WHITE}log monitoring${GREEN}: Fully integrated                ║${NC}"
                ;;
        esac
        echo -e "${GREEN}║                                                                               ║${NC}"
        echo -e "${GREEN}║  Useful Commands:                                                             ║${NC}"
        echo -e "${GREEN}║  • Health check: ${WHITE}/usr/local/bin/armguard-health-check${GREEN}                ║${NC}"
        echo -e "${GREEN}║  • Log monitor: ${WHITE}/usr/local/bin/armguard-log-monitor${GREEN}                  ║${NC}"
        if [ "$MONITORING_TYPE" != "minimal" ]; then
            echo -e "${GREEN}║  • System metrics: ${WHITE}/usr/local/bin/armguard-metrics${GREEN}                  ║${NC}"
        fi
        echo -e "${GREEN}║                                                                               ║${NC}"
        echo -e "${GREEN}║  🎉 ArmGuard deployment fully completed and monitored!                       ║${NC}"
        echo -e "${GREEN}║                                                                               ║${NC}"
        echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════════════════════╝${NC}"
    else
        echo ""
        log_warn "⚠️  Monitoring setup completed with warnings!"
        echo -e "${YELLOW}╔═══════════════════════════════════════════════════════════════════════════════╗${NC}"
        echo -e "${YELLOW}║                    ${WHITE}MONITORING SETUP - WARNINGS DETECTED${YELLOW}                    ║${NC}"
        echo -e "${YELLOW}║                                                                               ║${NC}"
        echo -e "${YELLOW}║  Some monitoring components may not be fully functional.                     ║${NC}"
        echo -e "${YELLOW}║  Basic health checks and log monitoring should still work.                   ║${NC}"
        echo -e "${YELLOW}║                                                                               ║${NC}"
        echo -e "${YELLOW}║  Check the deployment log for details: ${LOG_FILE}  ║${NC}"
        echo -e "${YELLOW}║                                                                               ║${NC}"
        echo -e "${YELLOW}╚═══════════════════════════════════════════════════════════════════════════════╝${NC}"
    fi
    
    echo ""
    log_info "Monitoring setup log saved to: $LOG_FILE"
    log_success "🎯 Complete modular deployment finished!"
}

# Execute main function
main "$@"