# ==============================================================================
# UNIFIED ENVIRONMENT CONFIGURATION GENERATOR
# ==============================================================================
# PURPOSE: Creates .env files compatible with Django application
# REPLACES: Hardcoded settings_production.py generation
# VERSION: 4.0.0 - Synchronized Configuration System
# ==============================================================================

param(
    [string]$NetworkType = "lan",
    [string]$Domain = "armguard.local",
    [string]$ServerIP = "192.168.1.100",
    [switch]$InteractiveMode = $true,
    [switch]$ProductionMode = $false
)

# ==============================================================================
# CONFIGURATION TEMPLATES
# ==============================================================================

$script:ENV_TEMPLATE = @"
# ============================================================
# ArmGuard Environment Configuration
# Generated by Unified Configuration System on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# ============================================================

# ============================================================
# Django Core Settings
# ============================================================

# Django Secret Key (GENERATED AUTOMATICALLY)
DJANGO_SECRET_KEY={SECRET_KEY}

# Debug mode (False for production, True for development)
DJANGO_DEBUG={DEBUG_MODE}

# Django Settings Module  
DJANGO_SETTINGS_MODULE={SETTINGS_MODULE}

# Allowed hosts (automatically configured for your deployment)
DJANGO_ALLOWED_HOSTS={ALLOWED_HOSTS}

# CSRF Trusted Origins (for HTTPS)
CSRF_TRUSTED_ORIGINS={CSRF_ORIGINS}

# ============================================================
# Enhanced Database Configuration
# ============================================================

# Database Engine Selection
DB_ENGINE={DB_ENGINE}

# PostgreSQL Settings  
DB_NAME={DB_NAME}
DB_USER={DB_USER}
DB_PASSWORD={DB_PASSWORD}
DB_HOST={DB_HOST}
DB_PORT={DB_PORT}

# Database Connection Security
DB_SSL_MODE={DB_SSL_MODE}

# Database Connection Pooling & Performance
DB_CONN_MAX_AGE={DB_CONN_MAX_AGE}
DB_MAX_CONNS={DB_MAX_CONNS}

# ============================================================
# Enhanced Security Configuration
# ============================================================

# Admin URL (Obfuscated for security)
DJANGO_ADMIN_URL={ADMIN_URL}

# Password Requirements
PASSWORD_MIN_LENGTH={PASSWORD_MIN_LENGTH}

# Enhanced Security Features
SECURITY_HEADERS_ENABLED={SECURITY_HEADERS}
REQUEST_LOGGING_ENABLED={REQUEST_LOGGING}
SINGLE_SESSION_ENFORCEMENT={SINGLE_SESSION}
RATE_LIMITING_ENABLED={RATE_LIMITING}

# SSL/HTTPS Settings
SECURE_SSL_REDIRECT={SSL_REDIRECT}
SESSION_COOKIE_SECURE={COOKIE_SECURE}
CSRF_COOKIE_SECURE={CSRF_SECURE}
SECURE_HSTS_SECONDS={HSTS_SECONDS}
SESSION_COOKIE_SAMESITE={COOKIE_SAMESITE}
CSRF_COOKIE_SAMESITE={CSRF_SAMESITE}

# Session Security  
SESSION_COOKIE_AGE={SESSION_AGE}
SESSION_EXPIRE_AT_BROWSER_CLOSE={SESSION_EXPIRE}

# Rate Limiting
RATELIMIT_ENABLE={RATE_LIMIT_ENABLE}
RATELIMIT_REQUESTS_PER_MINUTE={RATE_LIMIT_REQUESTS}

# Django Axes (Failed Login Protection)
AXES_ENABLED={AXES_ENABLED}
AXES_FAILURE_LIMIT={AXES_FAILURE_LIMIT}
AXES_COOLOFF_TIME={AXES_COOLOFF_TIME}

# Admin System Configuration
ADMIN_RESTRICTION_SYSTEM_ENABLED={ADMIN_RESTRICTIONS}
ADMIN_SESSION_TIMEOUT={ADMIN_SESSION_TIMEOUT}

# API Security Settings
API_RATE_LIMIT={API_RATE_LIMIT}
API_BURST_LIMIT={API_BURST_LIMIT}

# Device Authorization
DEVICE_AUTHORIZATION_ENABLED={DEVICE_AUTH}
DEVICE_ALLOW_ALL={DEVICE_ALLOW_ALL}

# File Upload Limits (in bytes)
FILE_UPLOAD_MAX_MEMORY_SIZE={FILE_UPLOAD_MAX}
DATA_UPLOAD_MAX_MEMORY_SIZE={DATA_UPLOAD_MAX}

# IP Whitelist for Admin Access (leave empty to disable)
ADMIN_ALLOWED_IPS={ADMIN_IPS}

# ============================================================
# Network Security Configuration
# ============================================================

# Network Type Configuration
NETWORK_TYPE={NETWORK_TYPE}
LAN_ONLY={LAN_ONLY}
WAN_PORTAL_ENABLED={WAN_PORTAL}

# Network Interface Configuration
LAN_INTERFACE={LAN_INTERFACE}
WAN_INTERFACE={WAN_INTERFACE}
SERVER_LAN_IP={SERVER_LAN_IP}
LAN_SUBNET={LAN_SUBNET}

# ============================================================
# Email Configuration (Optional)
# ============================================================

# Email Backend
EMAIL_BACKEND={EMAIL_BACKEND}

# SMTP Settings
EMAIL_HOST={EMAIL_HOST}
EMAIL_PORT={EMAIL_PORT}
EMAIL_USE_TLS={EMAIL_TLS}
EMAIL_HOST_USER={EMAIL_USER}
EMAIL_HOST_PASSWORD={EMAIL_PASSWORD}

# Email Addresses
DEFAULT_FROM_EMAIL={FROM_EMAIL}
SERVER_EMAIL={SERVER_EMAIL}
ADMIN_NAME={ADMIN_NAME}
ADMIN_EMAIL={ADMIN_EMAIL}

# ============================================================
# Admin Customization
# ============================================================

ADMIN_SITE_HEADER={ADMIN_HEADER}
ADMIN_SITE_TITLE={ADMIN_TITLE}
ADMIN_INDEX_TITLE={ADMIN_INDEX}

# ============================================================
# Logging Configuration  
# ============================================================

SECURITY_LOG_PATH={SECURITY_LOG}
ERROR_LOG_PATH={ERROR_LOG}
DJANGO_LOG_PATH={DJANGO_LOG}

# ============================================================
# Redis Configuration (Unified with app expectations)
# ============================================================

REDIS_HOST={REDIS_HOST}
REDIS_PORT={REDIS_PORT}
REDIS_PASSWORD={REDIS_PASSWORD}
REDIS_DB={REDIS_DB}

# ============================================================
# VPN Integration Settings (WireGuard)  
# ============================================================

WIREGUARD_ENABLED={WIREGUARD_ENABLED}
WIREGUARD_INTERFACE={WIREGUARD_INTERFACE}
WIREGUARD_NETWORK={WIREGUARD_NETWORK}
WIREGUARD_PORT={WIREGUARD_PORT}
VPN_EMAIL_ALERTS_ENABLED={VPN_EMAIL_ALERTS}
VPN_ALERT_EMAILS={VPN_ALERT_EMAILS}
VPN_MAX_CONCURRENT_CONNECTIONS={VPN_MAX_CONNECTIONS}

"@

# ==============================================================================
# CONFIGURATION GENERATORS
# ==============================================================================

function New-SecretKey {
    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*(-_=+)"
    $key = ""
    for ($i = 0; $i -lt 50; $i++) {
        $key += $chars[(Get-Random -Maximum $chars.Length)]
    }
    return $key
}

function New-AdminUrl {
    $chars = "abcdefghijklmnopqrstuvwxyz0123456789"
    $url = "admin-"
    for ($i = 0; $i -lt 12; $i++) {
        $url += $chars[(Get-Random -Maximum $chars.Length)]
    }
    return $url
}

function New-RedisPassword {
    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    $password = "armguard-redis-"
    for ($i = 0; $i -lt 16; $i++) {
        $password += $chars[(Get-Random -Maximum $chars.Length)]
    }
    return $password
}

function Get-ConfigurationValues {
    param(
        [string]$NetworkType,
        [string]$Domain, 
        [string]$ServerIP,
        [bool]$ProductionMode
    )
    
    # Generate secure values
    $secretKey = New-SecretKey
    $adminUrl = New-AdminUrl
    $redisPassword = New-RedisPassword
    $dbPassword = New-RedisPassword  # Use same generator for DB password
    
    # Network-specific configuration
    $allowedHosts = "127.0.0.1,localhost,$Domain,$ServerIP"
    $csrfOrigins = "https://$Domain,http://$Domain,https://$ServerIP,http://$ServerIP"
    
    if ($NetworkType -eq "lan") {
        $lanOnly = "True"
        $wanPortal = "False"
        $sslRedirect = "False"  # LAN typically uses HTTP
        $cookieSecure = "False"
        $csrfSecure = "False"
        $hstsSeconds = "0"
    } elseif ($NetworkType -eq "hybrid") {
        $lanOnly = "False"
        $wanPortal = "True"
        $sslRedirect = "True"
        $cookieSecure = "True"
        $csrfSecure = "True"
        $hstsSeconds = "31536000"
    } else {  # WAN
        $lanOnly = "False"
        $wanPortal = "True"
        $sslRedirect = "True"
        $cookieSecure = "True"
        $csrfSecure = "True"
        $hstsSeconds = "31536000"
    }
    
    # Build configuration hashtable
    return @{
        SECRET_KEY = $secretKey
        DEBUG_MODE = if ($ProductionMode) { "False" } else { "True" }
        SETTINGS_MODULE = if ($ProductionMode) { "core.settings_production" } else { "core.settings" }
        ALLOWED_HOSTS = $allowedHosts
        CSRF_ORIGINS = $csrfOrigins
        
        # Database Configuration (PostgreSQL optimized)
        DB_ENGINE = "django.db.backends.postgresql"
        DB_NAME = "armguard_db"
        DB_USER = "armguard_user"
        DB_PASSWORD = $dbPassword
        DB_HOST = "localhost"
        DB_PORT = "5432"
        DB_SSL_MODE = "prefer"
        DB_CONN_MAX_AGE = "600"
        DB_MAX_CONNS = "100"
        
        # Security Configuration
        ADMIN_URL = $adminUrl
        PASSWORD_MIN_LENGTH = if ($ProductionMode) { "12" } else { "8" }
        SECURITY_HEADERS = "True"
        REQUEST_LOGGING = "True" 
        SINGLE_SESSION = "True"
        RATE_LIMITING = "True"
        
        # SSL Configuration
        SSL_REDIRECT = $sslRedirect
        COOKIE_SECURE = $cookieSecure
        CSRF_SECURE = $csrfSecure
        HSTS_SECONDS = $hstsSeconds
        COOKIE_SAMESITE = "Strict"
        CSRF_SAMESITE = "Strict"
        
        # Session Configuration
        SESSION_AGE = "3600"  # 1 hour
        SESSION_EXPIRE = "True"
        
        # Rate Limiting
        RATE_LIMIT_ENABLE = "True"
        RATE_LIMIT_REQUESTS = "60"
        
        # Axes Configuration
        AXES_ENABLED = "True"
        AXES_FAILURE_LIMIT = "5"
        AXES_COOLOFF_TIME = "1"
        
        # Admin Configuration
        ADMIN_RESTRICTIONS = "True"
        ADMIN_SESSION_TIMEOUT = "3600"
        
        # API Security
        API_RATE_LIMIT = "100"
        API_BURST_LIMIT = "20"
        
        # Device Authorization
        DEVICE_AUTH = "True"
        DEVICE_ALLOW_ALL = "False"
        
        # File Upload Limits
        FILE_UPLOAD_MAX = "5242880"  # 5MB
        DATA_UPLOAD_MAX = "5242880"  # 5MB
        
        # Admin IPs (empty for no restriction)
        ADMIN_IPS = ""
        
        # Network Configuration
        NETWORK_TYPE = $NetworkType
        LAN_ONLY = $lanOnly
        WAN_PORTAL = $wanPortal
        LAN_INTERFACE = "eth1"
        WAN_INTERFACE = "eth0" 
        SERVER_LAN_IP = $ServerIP
        LAN_SUBNET = "192.168.10.0/24"
        
        # Email Configuration
        EMAIL_BACKEND = if ($ProductionMode) { "django.core.mail.backends.smtp.EmailBackend" } else { "django.core.mail.backends.console.EmailBackend" }
        EMAIL_HOST = "smtp.gmail.com"
        EMAIL_PORT = "587"
        EMAIL_TLS = "True"
        EMAIL_USER = ""
        EMAIL_PASSWORD = ""
        FROM_EMAIL = "noreply@$Domain"
        SERVER_EMAIL = "noreply@$Domain"
        ADMIN_NAME = "Admin"
        ADMIN_EMAIL = "admin@$Domain"
        
        # Admin Customization
        ADMIN_HEADER = "ArmGuard Administration"
        ADMIN_TITLE = "ArmGuard Admin"
        ADMIN_INDEX = "ArmGuard Dashboard"
        
        # Logging Paths
        SECURITY_LOG = "logs/security.log"
        ERROR_LOG = "logs/errors.log"
        DJANGO_LOG = "logs/django.log"
        
        # Redis Configuration (Secured)
        REDIS_HOST = "127.0.0.1"
        REDIS_PORT = "6379"
        REDIS_PASSWORD = $redisPassword
        REDIS_DB = "1"
        
        # VPN Configuration
        WIREGUARD_ENABLED = "False"
        WIREGUARD_INTERFACE = "wg0"
        WIREGUARD_NETWORK = "10.0.0.0/24"
        WIREGUARD_PORT = "51820"
        VPN_EMAIL_ALERTS = "False"
        VPN_ALERT_EMAILS = "admin@$Domain"
        VPN_MAX_CONNECTIONS = "50"
    }
}

function New-EnvironmentFile {
    param(
        [string]$OutputPath,
        [hashtable]$Config
    )
    
    $envContent = $script:ENV_TEMPLATE
    
    # Replace all placeholders with actual values
    foreach ($key in $Config.Keys) {
        $placeholder = "{$key}"
        $envContent = $envContent -replace [regex]::Escape($placeholder), $Config[$key]
    }
    
    # Write to file
    Set-Content -Path $OutputPath -Value $envContent -Encoding UTF8
    
    # Set secure permissions
    if (Test-Path $OutputPath) {
        try {
            $acl = Get-Acl $OutputPath
            $acl.SetAccessRuleProtection($true, $false)  # Disable inheritance
            $ownerRule = New-Object System.Security.AccessControl.FileSystemAccessRule($env:USERNAME, "FullControl", "None", "None", "Allow")
            $acl.SetAccessRule($ownerRule)
            Set-Acl -Path $OutputPath -AclObject $acl
        } catch {
            Write-Warning "Could not set secure permissions on .env file"
        }
    }
    
    return Test-Path $OutputPath
}

# ==============================================================================
# INTERACTIVE CONFIGURATION
# ==============================================================================

function Start-InteractiveConfiguration {
    Write-Host @"

═══════════════════════════════════════════════════════════════
🔧 ARMGUARD UNIFIED CONFIGURATION GENERATOR
═══════════════════════════════════════════════════════════════

This tool generates a complete .env file compatible with your
ArmGuard application, replacing hardcoded configuration approaches.

"@ -ForegroundColor Cyan

    # Network Type Selection
    Write-Host "🌐 Network Configuration:" -ForegroundColor White
    Write-Host "  1. LAN Only (Internal network, HTTP)"
    Write-Host "  2. WAN Only (Internet access, HTTPS)"
    Write-Host "  3. Hybrid (Both LAN and WAN with isolation)"
    Write-Host ""
    
    do {
        $networkChoice = Read-Host "Select network type (1-3) [1]"
        if (-not $networkChoice) { $networkChoice = "1" }
    } while ($networkChoice -notin @("1", "2", "3"))
    
    $networkType = switch ($networkChoice) {
        "1" { "lan" }
        "2" { "wan" }
        "3" { "hybrid" }
    }
    
    # Domain Configuration
    $defaultDomain = if ($networkType -eq "lan") { "armguard.local" } else { "login.yourdomain.com" }
    $domain = Read-Host "Domain name [$defaultDomain]"
    if (-not $domain) { $domain = $defaultDomain }
    
    # Server IP Configuration
    $defaultIP = "192.168.1.100"
    $serverIP = Read-Host "Server IP address [$defaultIP]"
    if (-not $serverIP) { $serverIP = $defaultIP }
    
    # Production Mode
    $prodChoice = Read-Host "Production mode? (y/n) [n]"
    $productionMode = $prodChoice -in @("y", "yes", "Y", "YES")
    
    return @{
        NetworkType = $networkType
        Domain = $domain
        ServerIP = $serverIP
        ProductionMode = $productionMode
    }
}

# ==============================================================================
# MAIN EXECUTION
# ==============================================================================

function Main {
    Write-Host "🔧 ArmGuard Unified Configuration Generator" -ForegroundColor Green
    
    # Get configuration parameters
    if ($script:InteractiveMode) {
        $config = Start-InteractiveConfiguration
        $NetworkType = $config.NetworkType
        $Domain = $config.Domain
        $ServerIP = $config.ServerIP
        $ProductionMode = $config.ProductionMode
    }
    
    # Generate configuration values
    Write-Host "🔄 Generating configuration values..." -ForegroundColor Yellow
    $configValues = Get-ConfigurationValues -NetworkType $NetworkType -Domain $Domain -ServerIP $ServerIP -ProductionMode $ProductionMode
    
    # Create .env file
    $envPath = Join-Path (Split-Path -Parent $script:ARMGUARD_ROOT) "armguard\.env"
    Write-Host "📝 Creating .env file: $envPath" -ForegroundColor Yellow
    
    $success = New-EnvironmentFile -OutputPath $envPath -Config $configValues
    
    if ($success) {
        Write-Host @"

═══════════════════════════════════════════════════════════════
✅ CONFIGURATION GENERATED SUCCESSFULLY
═══════════════════════════════════════════════════════════════

Generated Files:
  📄 Environment File: $envPath

Configuration Summary:
  🌐 Network Type: $NetworkType
  🏠 Domain: $Domain
  📡 Server IP: $ServerIP
  🔒 Production Mode: $ProductionMode
  🔐 Redis Password: $(if($configValues.REDIS_PASSWORD.Length -gt 20) { $configValues.REDIS_PASSWORD.Substring(0,20) + "..." } else { $configValues.REDIS_PASSWORD })
  🛡️ Admin URL: /$($configValues.ADMIN_URL)/

Security Features Enabled:
  ✅ Secure secret key generated
  ✅ Redis password authentication
  ✅ Database connection pooling
  ✅ Rate limiting configured
  ✅ Failed login protection (Axes)
  ✅ Enhanced security headers
  ✅ Session security
  ✅ Admin access controls

Next Steps:  
  1. Review .env file contents
  2. Adjust any settings as needed
  3. Run application with: python manage.py runserver
  4. Admin access: http://$Domain/$($configValues.ADMIN_URL)/

WARNING: Keep .env file secure! Never commit to version control.

═══════════════════════════════════════════════════════════════

"@ -ForegroundColor Green
    } else {
        Write-Host "❌ Failed to create configuration file" -ForegroundColor Red
        return 1
    }
    
    return 0
}

# Execute if run directly
if ($MyInvocation.InvocationName -ne '.') {
    $exitCode = Main
    exit $exitCode
}