"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# For development: generate with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = config('DJANGO_SECRET_KEY')  # No default - must be set in .env

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY FIX: Force DEBUG=False in production, only allow True in development
DEBUG_ENV = config('DJANGO_DEBUG', default=False, cast=bool)
DEBUG = DEBUG_ENV and not config('FORCE_PRODUCTION', default=False, cast=bool)

# SECURITY: Additional check to prevent accidental DEBUG=True in production
if config('DJANGO_SETTINGS_MODULE', default='') == 'core.settings_production':
    DEBUG = False

ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default='127.0.0.1,localhost,192.168.68.129,192.168.56.1,192.168.42.1,192.168.59.1,armguard.rds,testserver', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Security Apps
    'axes',  # Failed login attempt tracking
    # ArmGuard Apps
    'core',  # Added to register template tags
    'admin.apps.AdminConfig',
    'users',
    'personnel',
    'inventory',
    'transactions',
    'qr_manager',
    'print_handler',
    # VPN Integration
    'vpn_integration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'django_ratelimit.middleware.RatelimitMiddleware',
    # TODO: Implement these missing middleware classes:
    # 'core.middleware.StripSensitiveHeadersMiddleware',
    # 'core.middleware.AdminIPWhitelistMiddleware',
    # 'core.middleware.SecurityAuditMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.network_context.network_context',  # Network access context
                'vpn_integration.core_integration.vpn_context.vpn_context',  # VPN access context
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Conditional Database Configuration for Development/Production
USE_POSTGRESQL = config('USE_POSTGRESQL', default=False, cast=bool)

if USE_POSTGRESQL:
    # PostgreSQL for Production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='armguard'),
            'USER': config('DB_USER', default='armguard_user'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432', cast=int),
            'OPTIONS': {
                'connect_timeout': 20,
            },
        }
    }
else:
    # SQLite for Development/Testing
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation - Military Grade Security
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': config('PASSWORD_MIN_LENGTH', default=12, cast=int),  # Military standard
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication Backends (for Django Axes)
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Axes authentication backend
    'django.contrib.auth.backends.ModelBackend',  # Default backend
]


# Network-based Security Settings
# LAN/WAN hybrid architecture configuration

# Port configuration for network detection
NETWORK_PORTS = {
    'lan': 8443,  # Secure LAN operations
    'wan': 443,   # WAN status checking
}

# LAN-only paths (sensitive operations)
LAN_ONLY_PATHS = [
    '/admin/',
    '/admin',
    '/transactions/qr-scanner/',
    '/transactions/create/',
    '/transactions/edit/',
    '/transactions/delete/',
    '/inventory/add/',
    '/inventory/edit/',
    '/inventory/delete/',
    '/users/register/',
]

# WAN read-only paths (status checking)
WAN_READ_ONLY_PATHS = [
    '/personnel/',
    '/inventory/',
    '/reports/',
    '/transactions/history/',
    '/status/',
]

# Network access by user role
ROLE_NETWORK_RESTRICTIONS = {
    'admin': {'lan': True, 'wan': False},  # Admins need LAN access
    'staff': {'lan': True, 'wan': True},   # Staff can use both
    'user': {'lan': False, 'wan': True},   # Users only via WAN
}

# Session timeout by network type (minutes)
SESSION_TIMEOUT = {
    'lan': 120,  # 2 hours for LAN
    'wan': 30,   # 30 minutes for WAN
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'core' / 'static']

# Media files (User uploads - Pictures, QR Codes)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'core', 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ArmGuard Custom Settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Date and Time Formats (Military Time)
DATE_FORMAT = 'd/m/y'
DATETIME_FORMAT = 'd/m/y H:i:s'
USE_L10N = False

# Security Settings (Production)
# Development security settings (applied even in DEBUG mode for testing)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# For development - allow HTTP cookies
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_SECURE = False     # Set to True in production with HTTPS
SECURE_SSL_REDIRECT = False    # Set to True in production

# Enable these settings when deploying to production with HTTPS
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # SECURITY FIX: Add Content Security Policy headers
    CSP_DEFAULT_SRC = ("'self'",)
    CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'")  # Consider removing unsafe-inline in production
    CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
    CSP_IMG_SRC = ("'self'", "data:")
    CSP_FONT_SRC = ("'self'",)
    CSP_CONNECT_SRC = ("'self'",)
    CSP_FRAME_ANCESTORS = ("'none'",)

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = config('FILE_UPLOAD_MAX_MEMORY_SIZE', default=5242880, cast=int)  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = config('DATA_UPLOAD_MAX_MEMORY_SIZE', default=5242880, cast=int)  # 5MB

# Session Security - Enhanced for Military Environment
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'  # Prevent CSRF attacks
SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', default=1800, cast=int)  # 30 minutes for security
SESSION_SAVE_EVERY_REQUEST = True  # Reset timeout on each request
SESSION_EXPIRE_AT_BROWSER_CLOSE = config('SESSION_EXPIRE_AT_BROWSER_CLOSE', default=True, cast=bool)
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'  # Maximum CSRF protection
CSRF_COOKIE_AGE = 3600  # 1 hour CSRF token lifetime

# Rate Limiting Configuration
RATELIMIT_ENABLE = config('RATELIMIT_ENABLE', default=True, cast=bool)
RATELIMIT_REQUESTS_PER_MINUTE = config('RATELIMIT_REQUESTS_PER_MINUTE', default=60, cast=int)
RATELIMIT_STAFF_REQUESTS_PER_MINUTE = config('RATELIMIT_STAFF_REQUESTS_PER_MINUTE', default=300, cast=int)

# Django Axes Configuration (Failed Login Protection) - Military Grade
AXES_ENABLED = config('AXES_ENABLED', default=True, cast=bool)
AXES_FAILURE_LIMIT = config('AXES_FAILURE_LIMIT', default=3, cast=int)  # Reduced from 5 to 3
AXES_COOLOFF_TIME = config('AXES_COOLOFF_TIME', default=24, cast=int)  # 24 hours lockout for security
AXES_LOCKOUT_PARAMETERS = [["username"]]  # Lock by username globally (more secure)
AXES_RESET_ON_SUCCESS = True
AXES_ONLY_ADMIN_SITE = False  # Protect all login views
AXES_ENABLE_ACCESS_FAILURE_LOG = True
AXES_ENABLE_ADMIN = True  # Protect admin interface

# Cache Configuration (for rate limiting and Axes)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'armguard-cache',
    }
}

# Admin URL Configuration
ADMIN_URL_PREFIX = config('DJANGO_ADMIN_URL', default='admin-x7k2m9p-secret-portal-2026')

# Admin IP Whitelist (Optional - leave empty to disable)
ADMIN_ALLOWED_IPS = config('ADMIN_ALLOWED_IPS', default='', cast=Csv())

# =============================================================================
# VPN INTEGRATION SETTINGS
# =============================================================================

# Enable/disable VPN integration
WIREGUARD_ENABLED = config('WIREGUARD_ENABLED', default=False, cast=bool)
WIREGUARD_INTERFACE = config('WIREGUARD_INTERFACE', default='wg0')
WIREGUARD_NETWORK = config('WIREGUARD_NETWORK', default='10.0.0.0/24')
WIREGUARD_PORT = config('WIREGUARD_PORT', default=51820, cast=int)

# VPN Role-based access configuration
VPN_ROLE_RANGES = {
    'commander': {
        'ip_range': ('10.0.0.10', '10.0.0.19'),
        'access_level': 'VPN_INVENTORY_VIEW',
        'session_timeout': 7200,  # 2 hours
        'description': 'Commander remote inventory access'
    },
    'armorer': {
        'ip_range': ('10.0.0.20', '10.0.0.39'),
        'access_level': 'VPN_INVENTORY_VIEW',
        'session_timeout': 3600,  # 1 hour
        'description': 'Armorer remote inventory access'
    },
    'emergency': {
        'ip_range': ('10.0.0.40', '10.0.0.49'),
        'access_level': 'VPN_INVENTORY_LIMITED',
        'session_timeout': 1800,  # 30 minutes
        'description': 'Emergency limited inventory access'
    },
    'personnel': {
        'ip_range': ('10.0.0.50', '10.0.0.199'),
        'access_level': 'VPN_STATUS_ONLY',
        'session_timeout': 900,  # 15 minutes
        'description': 'Personnel status checking only'
    }
}

# VPN rate limiting (requests per minute by role)
VPN_RATE_LIMITS = {
    'commander': 100,
    'armorer': 50,
    'emergency': 200,
    'personnel': 30
}

# VPN Email alerts
VPN_EMAIL_ALERTS_ENABLED = config('VPN_EMAIL_ALERTS_ENABLED', default=False, cast=bool)
VPN_ALERT_EMAILS = config('VPN_ALERT_EMAILS', default='', cast=Csv())

# VPN Maximum concurrent connections
VPN_MAX_CONCURRENT_CONNECTIONS = config('VPN_MAX_CONCURRENT_CONNECTIONS', default=50, cast=int)

# User Registration Configuration
# SECURITY: Disabled by default for military systems - only admins can create accounts
ALLOW_PUBLIC_REGISTRATION = config('ALLOW_PUBLIC_REGISTRATION', default=False, cast=bool)
