# Generated by Django 5.1.1 on 2026-02-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stencil_picture',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/stencils/'),
        ),
    ]
