# Generated by Django 5.1.1 on 2026-02-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_stencil_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.PositiveIntegerField(blank=True, help_text='Item number (e.g. 1, 2, 3) within the same item type', null=True),
        ),
    ]
