# Generated by Django 5.1.1 on 2026-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='11-digit mobile number (e.g., 09171234567)', max_length=11, null=True),
        ),
    ]
