# Generated by Django 5.2.10 on 2026-01-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_manager', '0002_alter_qrcodeimage_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeimage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When QR was deactivated (soft delete)', null=True),
        ),
        migrations.AddField(
            model_name='qrcodeimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='QR code is active and can be used for transactions'),
        ),
    ]
