# Generated by Django 5.1.1 on 2026-01-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedrecord',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Reason for deletion (alias for compatibility)'),
        ),
        migrations.AddField(
            model_name='deletedrecord',
            name='record_name',
            field=models.CharField(default='', help_text='Name/identifier of deleted record', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('STATUS_CHANGE', 'Status Change'), ('ITEM_EDIT', 'Item Edit'), ('ITEM_DELETE', 'Item Delete'), ('USER_EDIT', 'User Edit'), ('USER_DELETE', 'User Delete'), ('PERSONNEL_EDIT', 'Personnel Edit'), ('PERSONNEL_DELETE', 'Personnel Delete')], max_length=20),
        ),
    ]
