# Generated by Django 5.1.1 on 2026-01-21 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('STATUS_CHANGE', 'Status Change')], max_length=20)),
                ('target_model', models.CharField(help_text='Model name (User, Personnel, etc.)', max_length=100)),
                ('target_id', models.CharField(help_text='ID of the affected record', max_length=100)),
                ('target_name', models.CharField(help_text='Name/identifier of the affected record', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('changes', models.JSONField(blank=True, help_text='Before/after values for updates', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='admin_app_a_timesta_bc3130_idx'), models.Index(fields=['target_model', 'target_id'], name='admin_app_a_target__c9b335_idx'), models.Index(fields=['performed_by', '-timestamp'], name='admin_app_a_perform_331d39_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeletedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=100)),
                ('record_data', models.JSONField(help_text='Complete record data before deletion')),
                ('reason', models.TextField(blank=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['-deleted_at'], name='admin_app_d_deleted_00ce23_idx'), models.Index(fields=['model_name', 'record_id'], name='admin_app_d_model_n_c5df36_idx')],
            },
        ),
    ]
