# Generated by Django 5.1.1 on 2026-02-11 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_deletedrecord_deletion_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAuthorizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Why do you need authorization for this device?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('security_level', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('STANDARD', 'Standard'), ('HIGH', 'High Security'), ('MILITARY', 'Military Grade')], default='STANDARD', max_length=20)),
                ('can_transact', models.BooleanField(default=True)),
                ('max_daily_transactions', models.IntegerField(default=50)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Authorization Request',
                'verbose_name_plural': 'Device Authorization Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
