# Generated by Django 5.2.x on 2026-02-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_deviceauthorizationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField()),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('security_level', models.CharField(choices=[('STANDARD', 'Standard'), ('RESTRICTED', 'Restricted'), ('HIGH_SECURITY', 'High Security')], default='RESTRICTED', max_length=20)),
                ('is_authorized', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deviceaccesslog',
            index=models.Index(fields=['-checked_at'], name='admin_app_de_checked_3ed8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaccesslog',
            index=models.Index(fields=['device_fingerprint', '-checked_at'], name='admin_app_de_device__6cf239_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaccesslog',
            index=models.Index(fields=['is_authorized', '-checked_at'], name='admin_app_de_is_auth_8be8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaccesslog',
            index=models.Index(fields=['ip_address', '-checked_at'], name='admin_app_de_ip_addr_9c20f7_idx'),
        ),
    ]
