# Generated by Django 5.1.1 on 2026-02-18 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_deviceaccesslog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deviceaccesslog',
            new_name='admin_app_d_checked_b21ad2_idx',
            old_name='admin_app_de_checked_3ed8bf_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceaccesslog',
            new_name='admin_app_d_device__094c83_idx',
            old_name='admin_app_de_device__6cf239_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceaccesslog',
            new_name='admin_app_d_is_auth_8e7a60_idx',
            old_name='admin_app_de_is_auth_8be8c6_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceaccesslog',
            new_name='admin_app_d_ip_addr_76881f_idx',
            old_name='admin_app_de_ip_addr_9c20f7_idx',
        ),
        migrations.AlterField(
            model_name='deviceaccesslog',
            name='checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
