# Generated by Django 5.1.1 on 2026-02-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_rename_admin_app_de_checked_3ed8bf_idx_admin_app_d_checked_b21ad2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceauthorizationrequest',
            name='csr_pem',
            field=models.TextField(blank=True, help_text='Optional PEM CSR submitted by requesting device'),
        ),
        migrations.AddField(
            model_name='deviceauthorizationrequest',
            name='issued_certificate_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceauthorizationrequest',
            name='issued_certificate_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceauthorizationrequest',
            name='issued_certificate_pem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deviceauthorizationrequest',
            name='issued_certificate_serial',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
