# Generated by Django 5.1.1 on 2026-02-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_deviceauthorizationrequest_csr_pem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceauthorizationrequest',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC address of the requesting network interface', max_length=64),
        ),
        migrations.AddField(
            model_name='deviceauthorizationrequest',
            name='pc_username',
            field=models.CharField(blank=True, help_text='OS login username of the requesting PC', max_length=255),
        ),
        migrations.AddField(
            model_name='deviceauthorizationrequest',
            name='system_specs',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-collected hardware/OS specs (CPU cores, RAM, OS, screen, etc.)'),
        ),
    ]
