# Generated by Django 5.1.1 on 2026-02-06 09:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, help_text='11-digit mobile number (e.g., 09171234567)', max_length=11, null=True)),
                ('group', models.CharField(blank=True, choices=[('HAS', 'HAS'), ('951st', '951st'), ('952nd', '952nd'), ('953rd', '953rd')], max_length=10, null=True)),
                ('badge_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_armorer', models.BooleanField(default=False)),
                ('is_restricted_admin', models.BooleanField(default=False, help_text='If True, administrator can only view but not edit/delete/create')),
                ('last_session_key', models.CharField(blank=True, help_text='Track last session for single session enforcement', max_length=40, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture (JPG, PNG, or GIF format)', null=True, upload_to='users/profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
