# Generated by Django 5.2.10 on 2026-02-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_department_userprofile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_restricted_admin',
            field=models.BooleanField(default=False, help_text='If True, administrator can only view but not edit/delete/create'),
        ),
    ]
