# Generated by Django 5.2.10 on 2026-02-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_is_restricted_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_session_key',
            field=models.CharField(blank=True, help_text='Track last session for single session enforcement', max_length=40, null=True),
        ),
    ]
