# Generated by Django 5.1.1 on 2026-01-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_personnel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='classification',
            field=models.CharField(choices=[('REGULAR', 'Regular Personnel'), ('SUPERUSER', 'Superuser'), ('ADMIN', 'Administrator')], default='REGULAR', help_text='Personnel classification (REGULAR, SUPERUSER, ADMIN)', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='rank',
            field=models.CharField(blank=True, choices=[('AM', 'Airman'), ('AW', 'Airwoman'), ('A2C', 'Airman 2nd Class'), ('AW2C', 'Airwoman 2nd Class'), ('A1C', 'Airman 1st Class'), ('AW1C', 'Airwoman 1st Class'), ('SGT', 'Sergeant'), ('SSGT', 'Staff Sergeant'), ('TSGT', 'Technical Sergeant'), ('MSGT', 'Master Sergeant'), ('SMSGT', 'Senior Master Sergeant'), ('CMSGT', 'Chief Master Sergeant'), ('2LT', 'Second Lieutenant'), ('1LT', 'First Lieutenant'), ('CPT', 'Captain'), ('MAJ', 'Major'), ('LTCOL', 'Lieutenant Colonel'), ('COL', 'Colonel'), ('BGEN', 'Brigadier General'), ('MGEN', 'Major General'), ('LTGEN', 'Lieutenant General'), ('GEN', 'General')], help_text='Military rank (not required for superusers)', max_length=20, null=True),
        ),
    ]
