# Generated by Django 5.1.1 on 2026-01-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_personnel_classification_alter_personnel_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='classification',
            field=models.CharField(choices=[('ENLISTED PERSONNEL', 'Enlisted Personnel'), ('OFFICER', 'Officer'), ('SUPERUSER', 'Superuser')], default='ENLISTED PERSONNEL', help_text='Personnel classification (ENLISTED PERSONNEL, OFFICER, SUPERUSER)', max_length=20),
        ),
    ]
