# Generated by Django 5.1.1 on 2026-01-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_alter_personnel_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='office',
        ),
        migrations.AddField(
            model_name='personnel',
            name='group',
            field=models.CharField(choices=[('HAS', 'HAS'), ('951st', '951st'), ('952nd', '952nd'), ('953rd', '953rd')], default='HAS', max_length=10),
        ),
    ]
