# Generated by Django 5.2.10 on 2026-01-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_remove_personnel_office_personnel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp - record kept for reference', null=True),
        ),
    ]
